source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

abstract_target ‘LTMarkdownParser_ExampleAbstract’ do
  platform :ios, ‘9.0’

  target ‘LTMarkdownParser_Example' do
    pod 'LTMarkdownParser', :path => '../'
    pod 'RichTextVC-iOS'
  end

  target ‘LTMarkdownParser_Tests' do
    pod 'LTMarkdownParser', :path => '../'
  end

end
