source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TSSwiftMarkdownParser_Example', :exclusive => true do
  pod 'TSSwiftMarkdownParser', :path => '../'
end

target 'TSSwiftMarkdownParser_Tests', :exclusive => true do
  pod 'TSSwiftMarkdownParser', :path => '../'
end
